import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";

import { PostHogProvider } from "~/server/posthog/provider";
import env from "~/env";
import { Toaster } from "sonner";
import ConvexClientProvider from "./convex";
import { ThemeProvider } from "../components/ui/themeProvider";
import { ThemeToggle } from "../components/ui/themeToggle";
import Link from "next/link";

export const metadata: Metadata = {
  title: env.NEXT_PUBLIC_TITLE,
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={geist.variable} suppressHydrationWarning>
      <body className="dark:bg-black">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <PostHogProvider>
              <ClerkProvider>
                <ConvexClientProvider>
                  <header className="bg-background/80 supports-[backdrop-filter]:bg-background/60 sticky top-0 z-30 w-full border-b backdrop-blur">
                    <div className="container mx-auto flex h-16 items-center justify-between gap-4 px-4">
                      <nav className="flex items-center gap-2">
                        <Link href="/">
                          <span className="text-lg font-bold">r5dan</span>
                        </Link>
                        <Link href="/blogs">
                          <span className="text-sm font-medium hover:underline">
                            Blogs
                          </span>
                        </Link>
                        <Link href="/projects">
                          <span className="text-sm font-medium hover:underline">
                            Projects
                          </span>
                        </Link>
                      </nav>
                      <div className="flex items-center gap-2">
                        <ThemeToggle />
                        <SignedOut>
                          <SignInButton />
                          <SignUpButton />
                        </SignedOut>
                        <SignedIn>
                          <UserButton />
                        </SignedIn>
                      </div>
                    </div>
                  </header>
                  {children}
                  <Toaster />
                </ConvexClientProvider>
              </ClerkProvider>
          </PostHogProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
