// "use client";

import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
// import {
//   Unauthenticated,
// } from "convex/react"

import { PostHogProvider } from "~/server/posthog/provider";
import env from "~/env";
import { Toaster } from "sonner";
import { ConvexClientProvider } from "./convex";
import { ThemeProvider } from "../components/themeProvider";
import { ThemeToggle } from "../components/themeToggle";
import Link from "next/link";
import { ImageKitProvider } from "@imagekit/next";

export const metadata: Metadata = {
  title: env.NEXT_PUBLIC_TITLE,
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={geist.variable} suppressHydrationWarning>
      <body className="dark:bg-black">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <PostHogProvider>
            <ImageKitProvider urlEndpoint="https://ik.imagekit.io/gg882iu3u/">
              <ConvexClientProvider>
                <header className="bg-background/80 supports-[backdrop-filter]:bg-background/60 sticky top-0 z-30 w-full border-b backdrop-blur">
                  <div className="container mx-auto flex h-16 items-center justify-between gap-4 px-4">
                    <nav className="flex items-center gap-2">
                      <Link href="/">
                        <span className="text-lg font-bold">r5dan</span>
                      </Link>
                      <Link href="/blogs">
                        <span className="text-sm font-medium hover:underline">
                          Blogs
                        </span>
                      </Link>
                      <Link href="/projects">
                        <span className="text-sm font-medium hover:underline">
                          Projects
                        </span>
                      </Link>
                    </nav>
                    <div className="flex items-center gap-2">
                      <ThemeToggle />
                      {/* <Unauthenticated>
                        <Link className="border-2 border-black" href="/auth/login">Login</Link>
                      </Unauthenticated> */}
                    </div>
                  </div>
                </header>
                {children}
                <Toaster />
              </ConvexClientProvider>
            </ImageKitProvider>
          </PostHogProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body className="bg-white">
//         {children}
//       </body>
//     </html>
//   );
// }
